//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAppSvc1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetail
    {
        public int InvoiceDetailId { get; set; }
        public string InvoiceId { get; set; }
        public string Item { get; set; }
        public decimal UnitPrice { get; set; }
        public int Qty { get; set; }
        public Nullable<decimal> SubAmount { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
